variables:
  WORK_DIR: e-questionare-frontend
  MAIN_BRANCH: main
  CLIENT_OVPN: 110.78.23.130
  VPN_USER: arcinstall
  VPN_PWD: P@ssW0rd123!@

deploy:
  only:
    - main
  stage: deploy

  before_script:
    - echo "Setup Open VPN"
    - which openvpn || (apk update && apk add openvpn && apk add iputils-ping)
    - cat <<< $CLIENT_OVPN > /etc/openvpn/client.ovpn
    - cat <<< $VPN_USER > /etc/openvpn/cred.txt
    - cat <<< $VPN_PWD >> /etc/openvpn/cred.txt 
    - openvpn --config /etc/openvpn/client.ovpn --auth-user-pass /etc/openvpn/cred.txt --daemon
    - sleep 30s
    - ping -c 1 $SERVER_IP
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd $WORK_DIR && git checkout $MAIN_BRANCH && git pull && exit"