variables:
  WORK_DIR: e-questionare-frontend
  MAIN_BRANCH: main


deploy:
  only:
    - main
  stage: deploy
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "cd $WORK_DIR && git checkout $MAIN_BRANCH && git pull && exit"